## Appveyor configuration for MoarVM

# We manually build and don't use MSVC's build process so disable it
build: off

platform:
  - x64
  - x86

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - appveyor-retry choco install strawberryperl --version 5.22.3.1 --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - perl Configure.pl --prefix=%APPVEYOR_BUILD_FOLDER%\buildprefix
  - nmake install
  - git clone https://github.com/perl6/nqp %APPVEYOR_BUILD_FOLDER%\nqp
  - cd %APPVEYOR_BUILD_FOLDER%\nqp
  - perl Configure.pl --prefix=%APPVEYOR_BUILD_FOLDER%\buildprefix
  - nmake
  - nmake install

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

branches:
  only:
    - master


#test_script:
#  - cd %APPVEYOR_BUILD_FOLDER%\nqp
#  - nmake m-test
