name: Test compile in Alpine
on: [push, pull_request]

jobs:
  compile:
    name: Compiles source

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        uses: JJ/alpine-moarvm-testbed@master

