name: Test compile in Alpine
on: [push, pull_request]

jobs:
  compile:
    runs-on:
      container:
        image: jjmerelo/alpine-moarvm-testbed
    name: Compiles source

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        run: perl Configure.pl && make

