name: Test compile in Alpine
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compiles source
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set container
        uses: JJ/raku-alpine-test@master
      - name: Compile
        run: perl Configure.pl && make
